import type { MockRunManifest } from "./types.js";
import { DEFAULT_AEGIS_CONFIG } from "../config/defaults.js";

function parseDefaultPiSettings(reference: string) {
  const separatorIndex = reference.indexOf(":");
  if (separatorIndex <= 0 || separatorIndex === reference.length - 1) {
    throw new Error(`Invalid default mock-run model reference: ${reference}`);
  }

  return {
    defaultProvider: reference.slice(0, separatorIndex),
    defaultModel: reference.slice(separatorIndex + 1),
  };
}

const DEFAULT_PI_SETTINGS = {
  ...parseDefaultPiSettings(DEFAULT_AEGIS_CONFIG.models.oracle),
  defaultThinkingLevel: DEFAULT_AEGIS_CONFIG.thinking.oracle,
};

export const TODO_BASELINE_FILES: Record<string, string> = {
  ".gitignore": [
    "# Beads / Dolt files (added by bd init)",
    ".dolt/",
    "*.db",
    ".beads-credential-key",
    ".aegis/config.json",
    ".aegis/dispatch-state.json",
    ".aegis/merge-queue.json",
    ".aegis/runtime-state.json",
    ".aegis/runtime-stop-request.json",
    ".aegis/labors/",
    ".aegis/logs/",
    ".aegis/mock-run-manifest.json",
    ".aegis/oracle/",
    ".aegis/titan/",
    ".aegis/sentinel/",
    ".aegis/janus/",
    ".aegis/merge-artifacts/",
    ".aegis/transcripts/",
  ].join("\n"),
  ".pi/settings.json": JSON.stringify(
    DEFAULT_PI_SETTINGS,
    null,
    2,
  ),
};

export const TODO_MOCK_RUN_ISSUES: MockRunManifest["issues"] = [
  {
    key: "todo-system",
    title: "React todo app program",
    description: "Program epic for autonomous delivery of a working React todo app from an empty repo baseline.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: null,
    blocks: [],
    labels: ["mock-run", "program"],
  },
  {
    key: "foundation",
    title: "Foundation slice",
    description: "Coordination epic for React scaffold and dependency baseline.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "foundation"],
  },
  {
    key: "foundation.contract",
    title: "[foundation] React scaffold contract",
    description: "Lock Vite React TypeScript scaffold contract, required scripts, and dependency policy.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: [],
    labels: ["mock-run", "foundation", "contract"],
  },
  {
    key: "foundation.lane_a",
    title: "[foundation] Lane A scaffold app shell",
    description: "Scaffold Vite React TypeScript project structure with deterministic source layout.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.contract"],
    labels: ["mock-run", "foundation", "lane_a"],
  },
  {
    key: "foundation.lane_b",
    title: "[foundation] Lane B install dependencies",
    description: "Install and lock React runtime/build dependencies and verify project scripts.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.contract"],
    labels: ["mock-run", "foundation", "lane_b"],
  },
  {
    key: "foundation.gate",
    title: "[foundation] Gate",
    description: "Prove scaffold and dependency baseline, then unlock todo domain implementation.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "foundation",
    blocks: ["foundation.lane_a", "foundation.lane_b"],
    labels: ["mock-run", "foundation", "gate"],
  },
  {
    key: "commands",
    title: "Domain slice",
    description: "Coordination epic for todo domain and storage behavior.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "commands"],
  },
  {
    key: "commands.contract",
    title: "[commands] Todo domain contract",
    description: "Define todo creation/list/complete behavior and storage contract for React app.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["foundation.gate"],
    labels: ["mock-run", "commands", "contract"],
  },
  {
    key: "commands.lane_a",
    title: "[commands] Lane A todo state/store",
    description: "Implement todo state model, reducers/hooks, and persistence integration.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.contract"],
    labels: ["mock-run", "commands", "lane_a"],
  },
  {
    key: "commands.lane_b",
    title: "[commands] Lane B domain validation/tests",
    description: "Implement domain validations and deterministic tests for add/list/complete flows.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.contract"],
    labels: ["mock-run", "commands", "lane_b"],
  },
  {
    key: "commands.gate",
    title: "[commands] Gate",
    description: "Prove todo domain slice and unlock UI integration.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "commands",
    blocks: ["commands.lane_a", "commands.lane_b"],
    labels: ["mock-run", "commands", "gate"],
  },
  {
    key: "integration",
    title: "Integration slice",
    description: "Coordination epic for UI integration, README, and localhost serving proof.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-system",
    blocks: [],
    labels: ["mock-run", "slice", "integration"],
  },
  {
    key: "integration.contract",
    title: "[integration] UI and serve contract",
    description: "Lock UI interaction contract, README content, and localhost run expectations.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["commands.gate"],
    labels: ["mock-run", "integration", "contract"],
  },
  {
    key: "integration.lane_a",
    title: "[integration] Lane A implement React UI",
    description: "Implement React todo UI with add/list/complete interactions and render-state behavior.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.contract"],
    labels: ["mock-run", "integration", "lane_a"],
  },
  {
    key: "integration.lane_b",
    title: "[integration] Lane B README and localhost serve proof",
    description: "Write README setup/run instructions and verify app serves on localhost with working UI.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.contract"],
    labels: ["mock-run", "integration", "lane_b"],
  },
  {
    key: "integration.gate",
    title: "[integration] Gate",
    description: "Prove complete working React todo app delivery with README and localhost serve evidence.",
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "integration",
    blocks: ["integration.lane_a", "integration.lane_b"],
    labels: ["mock-run", "integration", "gate"],
  },
];

export const TODO_READY_QUEUE_EXPECTATION = ["foundation.contract"] as const;

export const TODO_MOCK_RUN_MANIFEST: MockRunManifest = {
  repoName: "aegis-mock-run",
  beadsPrefix: "aegismockrun",
  baselineFiles: TODO_BASELINE_FILES,
  issues: TODO_MOCK_RUN_ISSUES,
  expectedInitialReadyKeys: [...TODO_READY_QUEUE_EXPECTATION],
};
