import type { MockRunManifest } from "./types.js";

export const TODO_MOCK_RUN_ISSUES: MockRunManifest["issues"] = [
  {
    key: "todo-webapp.program",
    title: "Polished animated todo app program",
    description: "Program epic for building a polished localhost React todo application from an empty repository.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: null,
    blocks: [],
    labels: ["mock-run", "program", "react", "todo"],
  },
  {
    key: "setup",
    title: "Foundation slice",
    description: "Coordination epic for project bootstrap, toolchain, and deterministic product foundation.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "setup"],
  },
  {
    key: "setup.contract",
    title: "[foundation] Product foundation brief",
    description: [
      "Write the product foundation brief for an animated React todo app.",
      "The generated app must feel like a finished todo product, not a framework starter.",
      "Visible UI must focus on adding, filtering, completing, deleting, and animating todos.",
      "Ban visible orchestration words from the product: gate, proof, lane, mounted, contract, shell, workspace, snapshot.",
    ].join("\n"),
    fileScope: ["docs/setup-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: [],
    labels: ["mock-run", "setup", "contract"],
  },
  {
    key: "setup.dependencies",
    title: "[foundation] Install dependencies",
    description: [
      "Install React runtime, Vite/TypeScript toolchain, animation libs, UI utility packages, and deterministic dev/build/preview npm scripts.",
      "Create package.json and package-lock.json from scratch if they do not exist; missing owned manifest files are local work, not blockers.",
      "Do not require build or preview checks to pass in this lane; scaffold and tooling lanes own those files.",
      "Do not create blockers for scaffold or tooling files already represented by downstream seeded setup issues.",
    ].join("\n"),
    fileScope: ["package.json", "package-lock.json"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.contract"],
    labels: ["mock-run", "setup", "lane_b", "deps"],
  },
  {
    key: "setup.scaffold",
    title: "[foundation] Scaffold product app",
    description: [
      "Scaffold a React + TypeScript localhost product app and baseline source tree.",
      "The first rendered screen must be a todo app, not a framework starter page.",
      "Use app title copy such as Animated Todo, Flow Todo, or Focus Todos; do not show framework, proof, or project-internal wording.",
      "Do not require build or preview checks to pass in this lane; tooling lane owns TypeScript/Vite config files.",
      "Do not create blockers for tooling files already represented by the downstream setup.tooling issue.",
    ].join("\n"),
    fileScope: [
      "index.html",
      "public/favicon.ico",
      "src/main.tsx",
      "src/App.tsx",
      "src/App.css",
      "src/index.css",
      "src/vite-env.d.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.dependencies"],
    labels: ["mock-run", "setup", "lane_a", "scaffold"],
  },
  {
    key: "setup.tooling",
    title: "[setup] Wire tooling",
    description: [
      "Configure linting, formatting, and test runner scripts for repeatable local development.",
      "Keep any format check scoped to owned tooling/package files in this lane.",
      "Before finalizing, run the formatter on owned tooling/package files and then prove npm run format:check is green.",
      "Do not format or rewrite src/ from this lane; source lanes own source formatting.",
    ].join("\n"),
    fileScope: [
      ".eslintrc.json",
      ".prettierrc",
      "package-lock.json",
      "package.json",
      "tsconfig.json",
      "tsconfig.node.json",
      "vite.config.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.scaffold"],
    labels: ["mock-run", "setup", "lane_c", "tooling"],
  },
  {
    key: "setup.gate",
    title: "[foundation] Integration check",
    description: "Validate foundation, dependencies, and tooling completion before feature implementation begins. Write internal notes only in docs; do not add visible product UI copy.",
    fileScope: [
      "docs/setup-gate.md",
      "docs/setup-contract.md",
      ".eslintrc.json",
      ".prettierrc",
      "package.json",
      "package-lock.json",
      "tsconfig.json",
      "tsconfig.node.json",
      "vite.config.ts",
      "index.html",
      "src/main.tsx",
      "src/App.tsx",
      "src/App.css",
      "src/index.css",
      "src/vite-env.d.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "setup",
    blocks: ["setup.scaffold", "setup.dependencies", "setup.tooling"],
    labels: ["mock-run", "setup", "gate"],
  },
  {
    key: "core",
    title: "Core logic slice",
    description: "Coordination epic for todo domain model, state management, and command behavior.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "core"],
  },
  {
    key: "core.contract",
    title: "[core] Contract seed",
    description: "Define todo model, persistence contract, and command semantics for create/toggle/delete flows.",
    fileScope: ["docs/core-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: [],
    labels: ["mock-run", "core", "contract"],
  },
  {
    key: "core.model",
    title: "[core] Lane A",
    description: "Implement todo entities, validation helpers, and deterministic ids/timestamps.",
    fileScope: ["src/domain/todo.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_a"],
  },
  {
    key: "core.state",
    title: "[core] Lane B",
    description: "Implement app state store with local persistence and selectors for filtered views.",
    fileScope: ["src/state/todo-store.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_b"],
  },
  {
    key: "core.commands",
    title: "[core] Lane C",
    description: "Implement create/toggle/delete/clear-completed commands with unit tests.",
    fileScope: ["src/state/todo-commands.ts", "src/state/todo-commands.test.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.contract"],
    labels: ["mock-run", "core", "lane_c"],
  },
  {
    key: "core.gate",
    title: "[core] Gate",
    description: "Prove core model/state/commands lanes and unlock UI implementation.",
    fileScope: [
      "docs/core-gate.md",
      "docs/core-contract.md",
      "src/domain/todo.ts",
      "src/state/todo-store.ts",
      "src/state/todo-commands.ts",
      "src/state/todo-commands.test.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "core",
    blocks: ["core.model", "core.state", "core.commands"],
    labels: ["mock-run", "core", "gate"],
  },
  {
    key: "ui",
    title: "UI slice",
    description: "Coordination epic for React components, layout, and interaction shell.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "ui"],
  },
  {
    key: "ui.contract",
    title: "[ui] Product interaction brief",
    description: [
      "Define component boundaries and product interaction requirements for a Todo app.",
      "The first viewport must clearly look like a polished todo application: product heading, todo input, list or empty state, filters, and counters.",
      "Ban visible orchestration words from UI copy: gate, proof, lane, mounted, contract, shell, workspace, snapshot.",
      "Keep implementation docs internal; users should only see todo-product language.",
    ].join("\n"),
    fileScope: ["docs/ui-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: [],
    labels: ["mock-run", "ui", "contract"],
  },
  {
    key: "ui.layout",
    title: "[ui] Product layout",
    description: [
      "Build the main product layout, responsive container, and semantic landmark structure.",
      "Use balanced spacing, clear sections, and wrapping that works at desktop and mobile widths.",
      "Keep the todo input and visible list/empty state near the top of the first viewport.",
      "Do not include setup, framework starter, or internal proof sections in the rendered UI.",
    ].join("\n"),
    fileScope: [
      "src/App.tsx",
      "src/components/AppShell.tsx",
      "src/components/AppShell.css",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["setup.gate", "core.gate", "ui.contract"],
    labels: ["mock-run", "ui", "lane_a"],
  },
  {
    key: "ui.components",
    title: "[ui] Todo controls",
    description: [
      "Implement todo list/item and input/filter components bound to core store commands.",
      "Todo items must be easy to scan, with complete and delete actions aligned and spaced as a cohesive product UI.",
      "Empty, active, and completed states must read as user-facing todo app states.",
    ].join("\n"),
    fileScope: [
      "src/components/TodoInput.tsx",
      "src/components/TodoList.tsx",
      "src/components/TodoItem.tsx",
      "src/components/TodoFilters.tsx",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["setup.gate", "core.gate", "ui.contract"],
    labels: ["mock-run", "ui", "lane_b"],
  },
  {
    key: "ui.accessibility",
    title: "[ui] Accessibility polish",
    description: "Add keyboard affordances, visible focus states, aria annotations, and screen-reader labels for the todo product.",
    fileScope: ["src/components/A11yStatus.tsx", "src/accessibility/keyboard.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["setup.gate", "core.gate", "ui.contract"],
    labels: ["mock-run", "ui", "lane_c", "a11y"],
  },
  {
    key: "ui.gate",
    title: "[ui] Product integration check",
    description: [
      "Integrate UI structure, component behavior, and accessibility before motion polish.",
      "Remove visible internal scaffolding copy and keep the product centered on todo management.",
      "The screen must not show gate/proof/lane/shell/workspace/contract language.",
    ].join("\n"),
    fileScope: [
      "docs/ui-gate.md",
      "docs/ui-contract.md",
      "src/App.tsx",
      "src/components/AppShell.tsx",
      "src/components/AppShell.css",
      "src/components/TodoInput.tsx",
      "src/components/TodoList.tsx",
      "src/components/TodoItem.tsx",
      "src/components/TodoFilters.tsx",
      "src/components/A11yStatus.tsx",
      "src/accessibility/keyboard.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "ui",
    blocks: ["ui.layout", "ui.components", "ui.accessibility"],
    labels: ["mock-run", "ui", "gate"],
  },
  {
    key: "motion",
    title: "Motion and polish slice",
    description: "Coordination epic for fancy animations, visual system, and interaction polish.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "motion"],
  },
  {
    key: "motion.contract",
    title: "[motion] Animation brief",
    description: [
      "Define animation choreography, reduced-motion fallback, and visual polish acceptance criteria.",
      "Animations must be observable add, complete, delete transitions on real todo items.",
      "Do not add separate demo panels or proof controls; motion belongs in the todo workflow.",
    ].join("\n"),
    fileScope: ["docs/motion-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: [],
    labels: ["mock-run", "motion", "contract"],
  },
  {
    key: "motion.item-animations",
    title: "[motion] Todo item transitions",
    description: [
      "Implement animated entry/exit/complete transitions for todo items.",
      "If exporting both a React component and an imperative DOM helper, keep React children typed/rendered as ReactNode inside JSX; only the DOM helper may append real DOM Nodes.",
    ].join("\n"),
    fileScope: ["src/motion/itemMotion.ts", "src/components/AnimatedTodoItem.tsx"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["ui.gate", "motion.contract"],
    labels: ["mock-run", "motion", "lane_a"],
  },
  {
    key: "motion.reorder-feedback",
    title: "[motion] List reflow feedback",
    description: "Implement smooth list reflow feedback for todo add/remove/filter changes without separate demo controls.",
    fileScope: ["src/motion/reorderMotion.ts", "src/components/ReorderFeedback.tsx"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["ui.gate", "motion.contract"],
    labels: ["mock-run", "motion", "lane_b"],
  },
  {
    key: "motion.visual-theme",
    title: "[motion] Visual polish",
    description: [
      "Implement refined color, shadows, typography, spacing, and density for a finished localhost todo product.",
      "Avoid one-note palettes and avoid decorative proof sections.",
    ].join("\n"),
    fileScope: ["src/styles/theme.css", "src/styles/theme.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["ui.gate", "motion.contract"],
    labels: ["mock-run", "motion", "lane_c"],
  },
  {
    key: "motion.gate",
    title: "[motion] Product animation check",
    description: [
      "Integrate animation and polish work into the real todo workflow.",
      "The app must show no visible orchestration vocabulary and no separate motion demo area.",
      "Todo add, completion, deletion, and filtering must remain usable after animation integration.",
    ].join("\n"),
    fileScope: [
      "docs/motion-gate.md",
      "docs/motion-contract.md",
      "src/App.tsx",
      "src/App.css",
      "src/components/TodoList.tsx",
      "src/components/TodoItem.tsx",
      "src/components/AnimatedTodoItem.tsx",
      "src/components/ReorderFeedback.tsx",
      "src/motion/itemMotion.ts",
      "src/motion/reorderMotion.ts",
      "src/styles/theme.css",
      "src/styles/theme.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "motion",
    blocks: ["motion.item-animations", "motion.reorder-feedback", "motion.visual-theme"],
    labels: ["mock-run", "motion", "gate"],
  },
  {
    key: "release",
    title: "Release slice",
    description: "Coordination epic for localhost run readiness, docs, and final acceptance proof.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "slice", "release"],
  },
  {
    key: "release.contract",
    title: "[release] Acceptance brief",
    description: [
      "Define done criteria for the finished localhost todo app including run command, build check, smoke steps, and product-quality checks.",
      "Acceptance must fail if visible UI contains orchestration vocabulary or framework starter copy.",
    ].join("\n"),
    fileScope: ["docs/release-contract.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: [],
    labels: ["mock-run", "release", "contract"],
  },
  {
    key: "release.localhost",
    title: "[release] Localhost run flow",
    description: [
      "Wire deterministic localhost run flow and production build validation commands.",
      "At this point the app gates are complete; inspect existing package/vite files before changing owned run configuration.",
    ].join("\n"),
    fileScope: ["package.json", "vite.config.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["setup.gate", "core.gate", "ui.gate", "motion.gate", "release.contract"],
    labels: ["mock-run", "release", "lane_a"],
  },
  {
    key: "release.verification",
    title: "[release] Browser verification",
    description: [
      "Add integration smoke checks proving todo flows and animation fallbacks under local run.",
      "Use Playwright to assert todo input/list/filter behavior, first-viewport product focus, and absence of visible orchestration vocabulary.",
    ].join("\n"),
    fileScope: ["tests/smoke/todo-flow.test.ts", "tests/smoke/reduced-motion.test.ts"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["setup.gate", "core.gate", "ui.gate", "motion.gate", "release.contract"],
    labels: ["mock-run", "release", "lane_b"],
  },
  {
    key: "release.docs",
    title: "[release] Runbook",
    description: "Write concise README runbook documenting setup, commands, and localhost app behavior.",
    fileScope: ["README.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["setup.gate", "core.gate", "ui.gate", "motion.gate", "release.contract"],
    labels: ["mock-run", "release", "lane_c"],
  },
  {
    key: "release.gate",
    title: "[release] Final product acceptance",
    description: [
      "Final acceptance: localhost app finished, documented, reproducibly runnable, and product-quality checked.",
      "Use Playwright/browser checks to prove the first viewport is the todo app, add/complete/delete/filter work, and no visible orchestration vocabulary remains.",
      "The final product must look like a cohesive animated todo app, not a collection of proof artifacts.",
    ].join("\n"),
    fileScope: [
      "docs/release-gate.md",
      "docs/release-contract.md",
      "README.md",
      "package.json",
      "package-lock.json",
      "vite.config.ts",
      "tests/smoke/todo-flow.test.ts",
      "tests/smoke/reduced-motion.test.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "release",
    blocks: ["release.localhost", "release.verification", "release.docs"],
    labels: ["mock-run", "release", "gate"],
  },
];

export const TODO_READY_QUEUE_EXPECTATION = [
  "setup.contract",
  "core.contract",
  "ui.contract",
  "motion.contract",
  "release.contract",
] as const;

export const TODO_MOCK_RUN_MANIFEST: MockRunManifest = {
  repoName: "aegis-mock-run",
  beadsPrefix: "aegismockrun",
  issues: TODO_MOCK_RUN_ISSUES,
  expectedInitialReadyKeys: [...TODO_READY_QUEUE_EXPECTATION],
};
