import type { MockRunManifest } from "./types.js";

export const TODO_MOCK_RUN_ISSUES: MockRunManifest["issues"] = [
  {
    key: "todo-webapp.program",
    title: "Animated todo app program",
    description: "Program epic for proving Aegis can drain a live Agora graph into a polished localhost React todo app.",
    issueType: "epic",
    priority: 1,
    queueRole: "coordination",
    parentKey: null,
    blocks: [],
    labels: ["mock-run", "program", "react", "todo"],
  },
  {
    key: "foundation.app",
    title: "[foundation] Build runnable React base",
    description: [
      "Create a Vite React TypeScript app foundation for a polished animated todo product.",
      "Install runtime, dev, test, animation, and Playwright dependencies with deterministic npm scripts: dev, build, lint, test, smoke, preview.",
      "Create source entry files and config files from scratch when absent.",
      "The product being built is a Todo app; visible UI must not show framework starter copy or orchestration vocabulary.",
      "Do not create blockers for product source files owned by later seeded issues.",
    ].join("\n"),
    fileScope: [
      "package.json",
      "package-lock.json",
      "index.html",
      "src/main.tsx",
      "src/vite-env.d.ts",
      "tsconfig.json",
      "tsconfig.node.json",
      "vite.config.ts",
      ".eslintrc.json",
      ".prettierrc",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "foundation", "product", "lane_a"],
  },
  {
    key: "core.todo",
    title: "[core] Implement todo model and state",
    description: [
      "Implement todo entities, validation, deterministic id/timestamp helpers, local persistence, selectors, and create/toggle/delete/clear-completed commands.",
      "Include focused unit tests for todo command behavior.",
      "Keep this lane independent from React UI; expose clean functions/components can consume.",
    ].join("\n"),
    fileScope: [
      "src/domain/todo.ts",
      "src/state/todo-store.ts",
      "src/state/todo-commands.ts",
      "src/state/todo-commands.test.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: [],
    labels: ["mock-run", "core", "todo", "lane_b"],
  },
  {
    key: "ui.components",
    title: "[ui] Build todo product components",
    description: [
      "Build Todo app components for first viewport product use: heading, todo input, filter controls, counters, empty state, list, item complete/delete actions, and accessibility status.",
      "Ban visible orchestration words from UI copy: gate, proof, lane, mounted, contract, shell, workspace, snapshot.",
      "The first viewport must clearly look like a polished Todo app, not a framework starter page.",
      "Wire components to the core todo model/store APIs without editing App integration files.",
    ].join("\n"),
    fileScope: [
      "src/components/AppShell.tsx",
      "src/components/AppShell.css",
      "src/components/TodoInput.tsx",
      "src/components/TodoList.tsx",
      "src/components/TodoItem.tsx",
      "src/components/TodoFilters.tsx",
      "src/components/A11yStatus.tsx",
      "src/accessibility/keyboard.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["foundation.app", "core.todo"],
    labels: ["mock-run", "ui", "product", "lane_c"],
  },
  {
    key: "motion.polish",
    title: "[motion] Add animation and visual polish",
    description: [
      "Implement observable add, complete, delete transitions and filter reflow on real todo items.",
      "Add reduced-motion fallbacks plus refined color, shadows, typography, spacing, and density for a finished localhost todo product.",
      "Avoid one-note palettes and separate demo panels; motion belongs in the todo workflow.",
    ].join("\n"),
    fileScope: [
      "src/motion/itemMotion.ts",
      "src/motion/reorderMotion.ts",
      "src/components/AnimatedTodoItem.tsx",
      "src/components/ReorderFeedback.tsx",
      "src/styles/theme.css",
      "src/styles/theme.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["foundation.app", "core.todo"],
    labels: ["mock-run", "motion", "polish", "lane_d"],
  },
  {
    key: "app.integration",
    title: "[app] Integrate finished todo workflow",
    description: [
      "Integrate foundation, core, UI components, motion, and theme into the main React app.",
      "The rendered page must be a cohesive animated Todo app with add, complete, delete, clear-completed, filter, counter, empty, active, and completed states.",
      "Remove starter copy and visible internal scaffolding language.",
      "Run relevant local checks available at this point and record results in the Titan artifact.",
    ].join("\n"),
    fileScope: [
      "src/App.tsx",
      "src/App.css",
      "src/index.css",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["ui.components", "motion.polish"],
    labels: ["mock-run", "integration", "product", "lane_e"],
  },
  {
    key: "release.smoke",
    title: "[release] Add browser smoke proof",
    description: [
      "Add Playwright smoke checks proving todo input/list/filter behavior, first-viewport product focus, reduced-motion fallback, and absence of visible orchestration vocabulary.",
      "Use localhost app behavior as the product proof center.",
      "Do not broaden into unrelated test harness work.",
    ].join("\n"),
    fileScope: [
      "playwright.config.ts",
      "tests/smoke/todo-flow.test.ts",
      "tests/smoke/reduced-motion.test.ts",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["app.integration"],
    labels: ["mock-run", "release", "smoke", "lane_f"],
  },
  {
    key: "janus.integration",
    title: "[janus] Integration runbook lane",
    description: [
      "Keep Janus in the live proof path by landing a merge-boundary runbook after app integration.",
      "Write concise README commands and expected localhost todo behavior.",
      "If this lane hits merge/integration conflict, Janus must preserve artifacts and route deterministic rework instead of hiding the failure.",
    ].join("\n"),
    fileScope: ["README.md"],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["app.integration"],
    labels: ["mock-run", "janus", "release", "lane_g"],
  },
  {
    key: "release.final",
    title: "[release] Final product acceptance",
    description: [
      "Final acceptance for the drained localhost app.",
      "Run install/build/test/smoke checks available in package scripts and verify the app presents as a polished animated todo product.",
      "Use Playwright/browser checks to prove first viewport Todo app focus, add/complete/delete/filter behavior, and no visible orchestration vocabulary.",
      "The final product must look cohesive, not like a collection of proof artifacts.",
    ].join("\n"),
    fileScope: [
      "docs/final-product-notes.md",
    ],
    issueType: "task",
    priority: 1,
    queueRole: "executable",
    parentKey: "todo-webapp.program",
    blocks: ["release.smoke", "janus.integration"],
    labels: ["mock-run", "release", "final", "gate"],
  },
];

export const TODO_READY_QUEUE_EXPECTATION = [
  "foundation.app",
  "core.todo",
] as const;

export const TODO_MOCK_RUN_MANIFEST: MockRunManifest = {
  repoName: "aegis-mock-run",
  beadsPrefix: "aegismockrun",
  issues: TODO_MOCK_RUN_ISSUES,
  expectedInitialReadyKeys: [...TODO_READY_QUEUE_EXPECTATION],
};
